db:
  hostname: db
  port: 5432
  user: rss_user
  password_path: ./dbpw.env
  db_name: rss_db
api:
  hostname: localhost
  port: 3000
  openapi_server: localhost
  openapi_port: 3000
cors:
  origins: http://localhost:3000
  methods: GET,POST,PATCH,DELETE,OPTIONS,HEAD
